#!/bin/sh
rosbag record -O pool \
/diagnostics \
/joint_states \
/l_forearm_cam/camera_info \
/l_forearm_cam/image_rect_color \
/r_forearm_cam/camera_info \
/r_forearm_cam/image_rect_color \
/narrow_stereo_textured/points \
/narrow_stereo_textured/left/camera_info \
/narrow_stereo_textured/left/image_raw \
/narrow_stereo_textured/right/camera_info \
/narrow_stereo_textured/right/image_raw \
/wide_stereo/left/camera_info \
/wide_stereo/left/image_raw \
/wide_stereo/left/image_rect_color \
/wide_stereo/right/camera_info \
/wide_stereo/right/image_raw \
/wide_stereo/right/image_rect_color \
/tilt_scan \
/prosilica_offset/camera_info \
/prosilica_offset/image_rect_color \
/tf
